name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit message to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embeds: |
            [
              {
                "title": "New Commit Pushed",
                "url": "${{ github.event.head_commit.url }}",
                "color": 7506394,
                "author": {
                  "name": "${{ github.event.head_commit.author.name }}",
                  "icon_url": "${{ github.event.head_commit.author.avatar_url }}",
                  "url": "https://github.com/${{ github.event.head_commit.author.username }}"
                },
                "fields": [
                  {
                    "name": "Repository",
                    "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})",
                    "inline": true
                  },
                  {
                    "name": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}"
                  }
                ],
                "footer": {
                  "text": "Automated by GitHub Actions"
                },
                "timestamp": "${{ github.event.head_commit.timestamp }}"
              }
            ]
