name: Notify Discord on Push

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  notify:
    runs-on: ubuntu-latest

steps:
  - name: Notify Discord
    uses: Ilshidur/action-discord@v2
    with:
      webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
      message: |
        New commit pushed by ${{ github.actor }} to ${{ github.repository }}.
        Commit message: ${{ github.event.head_commit.message }}
