name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit message to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            **New commit pushed by** `${{ github.actor }}`  
            Repository: `${{ github.repository }}`  
            Commit message: `${{ github.event.head_commit.message }}`
