name: Update status.json on push

on:
  push:
    branches:
      - main

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update status.json
        run: |
          user="${{ github.actor }}"
          time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "{\"message\": \"Latest commit by $user at $time\"}" > ./api/status/status.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./api/status/status.json
          git commit -m "Update status.json: latest commit by ${{ github.actor }} at $time" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
